config/routes.rb
Rails.application.routes.draw do
  devise_for :org_people, :controllers => {
    :registrations => "org_people/registrations",
    :sessions => "org_people/sessions",
    :passwords => "org_people/passwords" ,
    :confirmations => "org_people/confirmations" }
  devise_scope :org_person do
    get 'signup',  to: 'org_people/registrations#new'
    get 'signin',  to: 'org_people/sessions#new'
    delete 'signout', to: 'org_people/sessions#destroy'
  end

  get 'catalogues/index'
  post 'carts/add/' => 'carts#add', :to => 'carts_add'
  post 'carts/add_delivery_method' => 'carts#add_delivery_method', :to => 'carts_add_delivery_method'

  get 'org_companies/:id/company_profile' => 'org_companies#company_profile', :as => 'org_companies_company_profile'
  get 'org_companies/people/' => 'org_companies#people', :to => "org_companies_people"
  get 'org_companies/list_deliverers/' => 'org_companies#list_deliverers', :to => "org_companies_list_deliverers"
  get 'org_companies/preferred_deliverers/' => 'org_companies#preferred_deliverers', :to => "org_companies_preferred_deliverers"
  post 'org_companies/ajax_add_deliverers/' => 'org_companies#ajax_add_deliverers', :to => "org_companies_ajax_add_deliverers"
  post 'org_companies/remove_preferred_deliverers/' => 'org_companies#remove_preferred_deliverers', :to => "org_companies_remove_preferred_deliverers"

  post 'org_products/delivery_status/' => 'org_products#delivery_status', :to => "org_products_delivery_status"
  post 'org_products/send_product_ready_email/' => 'org_products#send_product_ready_email', :to => "org_products_send_product_ready_email"
  post 'org_products/vote_product/' => 'org_products#vote_product', :to => "org_products_vote_product"
  get 'org_products/orders/' => 'org_products#orders', :to => "org_products_orders"
  get 'org_products/completed_orders/' => 'org_products#completed_orders', :to => "org_products_completed_orders"

  get 'org_people/stripe_settings/' => 'org_people#stripe_settings', :to => "org_people_stripe_settings"
  post 'org_people/stripe_update_settings/' => 'org_people#stripe_update_settings', :to => "org_people_stripe_update_settings"
  post 'org_people/edit_position/' => 'org_people#edit_position', :to => "org_people_edit_position"
  post 'org_people/remove_from_company/' => 'org_people#remove_from_company', :to => "org_people_remove_from_company"

  post 'trx_orders/stripe/' => 'trx_orders#stripe', :to =>"trx_orders_stripe"
  get 'trx_orders/stripe_success/:id' => 'trx_orders#stripe_success', :to => "trx_orders_stripe_success"
  get 'trx_orders/list_purchases/' => 'trx_orders#list_purchases', :to => "trx_orders_list_purchases"
  get 'trx_orders/list_personal_purchases/' => 'trx_orders#list_personal_purchases', :to => "trx_orders_list_personal_purchases"
  get 'trx_orders/purchase_order/' => 'trx_orders#purchase_order', :to => "trx_orders_purchase_order"


  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'
  
  post '/hooks/stripe' => 'hooks#stripe'


  post 'trx_orders/hook' => 'trx_orders#hook', :to => "trx_orders_hook"
  root "catalogues#index"

  resources :org_products
  resources :org_companies
  resources :org_people
  resources :trx_orders
  resources :carts
  resources :catalogues
  resources :sessions, only: [:new, :create, :destroy]


  match '/org_register', to:'org_companies#new', via: 'get'
end

app/models/trx_order.rb
class TrxOrder < ActiveRecord::Base
	has_many :TrxOrderItem
	has_many :TrxOrderFee
	has_many :StripeTransaction
	belongs_to :bill_to_contact, class_name: 'OrgContact'
	belongs_to :ship_to_contact, class_name: 'ShippingAddress'
	serialize :notification_params

	private
end

app/controllers/trx_orders_controller.rb
class TrxOrdersController < ApplicationController
	protect_from_forgery except: [:hook]
	before_action :signed_in_user, only: [:index, :new, :create, :edit, :update, :delete, :stripe, :stripe_success, :list_purchases, :purchase_order]
	before_action :user_has_role_in_company?, only: [:list_purchases]

	def index
		@cart = Cart.where(org_person_id: current_org_person.id) #Grab whatever is in the cart
		if @cart.empty? # If there is nothing attached to this user
			@cart = session[:cart] # See if there's anything in the session.
			session[:cart] = nil # Empty out the session
			if !@cart.nil? # If the cart is not empty
				@cart.each do |c| # Create each item in the session cart in the DB and attach to current user.
					Cart.create(org_person_id: current_org_person.id,
								org_product_id: c[1]["id"],
								name: c[1]["title"],
								tax_amount: c[1]["tax_amount"],
								price: c[1]["price"].to_f, 
			                    grocer: c[1]["grocer"],
			                    quantity: c[1]["quantity"],
			                    weight_in_grams: c[1]["weight"],
			                    expiry_date: c[1]["expiry"])
				
				end 
			end
		end
		@fee = total_projectmeal_fee
		@cart = Cart.where(org_person_id: current_org_person.id) # Just in case we removed anything during our sanitization period with stripe_vendor_charges
		@subtotal = get_subtotal(@cart) # Calculate the total for it
		@total_tax = get_total_tax(@cart)
		@currency = Money.new(1, session[:currency]["iso_code"]).currency # Gives us the currency symbol to display in the view
	end

	def stripe
		billing = {
			name: params["stripeBillingName"],
			address: {
				line1: params["stripeBillingAddressLine1"],
				postal_code: params["stripeBillingAddressZip"],
				city: params["stripeBillingAddressCity"],
				region: params["stripeBillingAddressState"],
				country: params["stripeBillingAddressCountryCode"],
			}	
		}

		shipping = {
			name: params["stripeShippingName"],
			address: {
				line1: params["stripeShippingAddressLine1"],
				postal_code: params["stripeShippingAddressZip"],
				city: params["stripeShippingAddressCity"],
				state: params["stripeShippingAddressState"],
				country: params["stripeShippingAddressCountryCode"],
			}
		}

		Stripe.api_key = ENV['STRIPE_SECRET_KEY']

		@customer = Stripe::Customer.create(
			:email => params[:stripeEmail],
			:source => params[:stripeToken]
		)
		stripeTransactions = Array.new # Array used so later we can update the StripeTransactions with their TrxOrder id
		amount_total = 0 # Keep track of the total
		session[:svc].each do |key, array|
			token = Stripe::Token.create({:customer => @customer.id}, {:stripe_account => array['stripe_id']})

			# Charge the customer instead of the card
			charge = Stripe::Charge.create(
				{  	:source 	=> token.id,
					:amount 	=> (array['total']*100).to_i,
					:description => 'Cart Purchase',
					:currency	=> session[:currency]['iso_code'],
					:shipping 	=> shipping,
					:application_fee => (array['fee']*100).to_i
				}, {:stripe_account => array['stripe_id']}
			)

			# If the charge succeeded, then record the data
			if charge[:paid]
				stripeCharge = {
					txn_type: charge[:object],
					currency: charge[:currency],
					total_amount: charge[:amount],
					tax_amount: array['tax']*100.to_i,
					notification_params: charge,
					txn_id: charge[:id],
					status: charge[:paid],
					description: charge[:description] 
				}
				amount_total = amount_total + (array['total']*100).to_i # Keep track of the total
				@sT = StripeTransaction.create(stripeCharge) # make a record in the StripeTransactions table
				stripeTransactions << @sT.id # push the id into the stripeTransactions array for later use
			end
		end


		if !stripeTransactions.empty? # If our stripeTransactions array is not empty, we made some transactions
			@orderInfo = { # Gather the following information
				org_company_id: current_org_person.org_company_id.nil? ? nil : current_org_person.org_company_id,
				bill_to_contact_id: current_org_person.id,
				purchased_at: Time.now,
				total_amount: amount_total,
				transport_method: session[:delivery_method]
			}
			@order = TrxOrder.create(@orderInfo)
			StripeTransaction.where(id:stripeTransactions).update_all(trx_order_id: @order.id) #Update all the records of stripeTransactions with trx_order_id: @order.id
			trx_order_fee = {
				fee_amount: total_projectmeal_fee, #get the fees of all stripe_transcactions for this order
				trx_order_id: @order.id
			}
			@trx_order_fee = TrxOrderFee.create(trx_order_fee)
			@shipAddress = {
				first_name:params["stripeShippingName"],
				last_name:params["stripeShippingName"],
				address1: params["stripeShippingAddressLine1"],
				city: params["stripeShippingAddressCity"],
				region: params["stripeShippingAddressState"],
				postal_code: params["stripeShippingAddressZip"],
				country: params["stripeShippingAddressCountryCode"],
				email: params["stripeEmail"],
				trx_order_id: @order.id
			}
			@shipInfo = ShippingAddress.create!(@shipAddress)
			@order.update(ship_to_contact_id: @shipInfo.id, trx_order_fee_id: @trx_order_fee.id) #Update the order with the new shipping address id
		end

		if !@shipInfo.nil?
			product_sold(@order, @shipInfo)
			session.delete(:svc) # Clean up sessions
			redirect_to action: "stripe_success", id: @order.id
		else
			render :index
		end
		rescue Stripe::CardError => expiry_date
			flash[:error] = e.message
			redirect_to trx_order_path
	end

	# Grabs all the necessary data and presents an invoice display page after purchases
	def stripe_success
		@order = TrxOrder.find(params[:id])
		@pm_fee = TrxOrderFee.find_by_id(@order.trx_order_fee_id)
		# Only the purchaser can see this information
		if current_org_person.id == @order.bill_to_contact_id || current_org_person.org_company_id == @order.org_company_id
			@company = !@order.org_company_id.nil? ? OrgCompany.find(@order.org_company_id) : nil
			@shipAddress = ShippingAddress.find_by(trx_order_id: params[:id])
			@purchase_items = @order.TrxOrderItem.all
			@notification_params_name = JSON.parse(@order.StripeTransaction.all[0][:notification_params])["source"]["name"]
			@total_tax = @order.TrxOrderItem.sum(:tax_amount).to_f
			@currency = Money.new(1, session[:currency]['iso_code']).currency # Gives us the currency symbol to display in the view
			@contact = current_org_person
			invoice_details_hash = { order: @order,
				company: @company,
				shipAddress: @shipAddress,
				purchase_items: @purchase_items,
				notification_params: @notification_params_name,
				total_tax: @total_tax,
				currency: @currency, 
				billed_contact: @contact,
				pm_fee: @pm_fee
			}

			Cart.destroy_all(org_person_id: current_org_person.id)
			InvoiceMailer.invoice_details(invoice_details_hash).deliver_now
			respond_to do |format|
				format.html
				format.pdf do 
					render pdf: "Invoice ##{@order.id}",
						template: "trx_orders/purchase_order.pdf.erb"
				end
			end
		else
			redirect_to root_path, flash: {warning: "You are not authorized to view this page."}
		end
	end

	# For sidebar use, to list all the personal purchases made by user
	def list_personal_purchases
		@purchases = TrxOrder.where(bill_to_contact_id:current_org_person.id).to_a
		@currency = Money.new(1, session[:currency]['iso_code']).currency # Gives us the currency symbol to display in the view
	end

	# For sidebar use, to list all the company purchases made by user
	def list_purchases
		@purchases = TrxOrder.where(org_company_id:current_org_person.org_company_id).to_a
		@currency = Money.new(1, session[:currency]['iso_code']).currency # Gives us the currency symbol to display in the view
	end

	def purchase_order
		@order = TrxOrder.find_by(id:params[:id])
		@pm_fee = TrxOrderFee.find_by_id(@order.trx_order_fee_id)
		# Only the purchaser can see this information
		if current_org_person.id == @order.bill_to_contact_id || current_org_person.org_company_id == @order.org_company_id
			@company = !@order.org_company_id.nil? ? OrgCompany.find_by(id: @order[:org_company_id]) : nil
			@shipAddress = ShippingAddress.find_by(trx_order_id: params[:id])
			@purchase_items = TrxOrderItem.where(trx_order_id: @order[:id])
			@notification_params_name = JSON.parse(@order.StripeTransaction.all[0][:notification_params])["source"]["name"]
			@total_tax = @order.TrxOrderItem.sum(:tax_amount).to_f
			@currency = Money.new(1, session[:currency]['iso_code']).currency # Gives us the currency symbol to display in the view
			@contact = current_org_person
			respond_to do |format|
				format.html
				format.pdf do
					render pdf: "Invoice ##{@order.id}",
						template: "trx_orders/purchase_order.pdf.erb"
				end
			end
		else
			redirect_to root_path, flash: {warning: "You are not authorized to view this page."}
		end
	end

	private
	# Reduce the quantity for the specific items bought in the db and insert the bought items 
	# into trx_order_items table with trx_order_id
	def product_sold(order, sa)
		@cart_item = Cart.where(org_person_id: current_org_person.id)  # Grab whatever is in the cart
		array = Array.new  # Make a new array for holding ids
		@cart_items.each do |id| # Throw all id's into the array
			array << id[:org_product_id].to_i
		end

		@products = OrgProduct.where(id:array) # Find all the products with the id array
		# For each product
		@products.each_with_index do |product, index|

			q = @cart_items.find{ |item| item.org_product_id == product.id}
			#Update the quantity available in OrgProduct after the sale and save.
			product.available_quantity = product.available_quantity.to_i - q.quantity
			product.save
			# Create the hash for insert into trx_order_items
			order_item = {
				name: product.name,
				description: product.description,
				weight_in_grams: product.weight_in_grams,
				price: product.price,
				available_quantity: product.available_quantity,
				quantity: q.quantity,
				expiry_date: product.expiry_date,
				image: product.image,
				delivery_status: 0,

app/views/trx_orders/index.html.erb
<div class="col-md-6 col-md-push-3">
  <%= provide(:title, "Checkout") %>
  <center><h1>Checkout</h1></center>
</div>

<div class="col-md-9 col-md-offset-2 main">
<% if  @cart.nil? %>
	<h3 class="col-md-9 col-md-offset-2 main">There are no items in your cart to checkout.</h3>
<% else %>
	<ul class="catalogue">
		<li>
			<div class="row">
				<h4 class="col-md-3" id="prodInfo">
		            Order Details
		        </h4>
		        <h4 class="col-md-3 col-md-push-1">
		        	Quantity
		        </h4>
		        <h4 class="col-md-3 col-md-push-1">
		        	Tax
		        </h4>
		        <h4 class="col-md-3 col-md-push-1">
		        	Total
		        </h4>
			</div>
		</li>
		<% @cart.each do |product| %>
		<li>
			<div class="row">
				<div class="col-md-3" id="co_prodInfo">
					<span>Product: <%= product["name"]%></span>
					<span>Price: <%= @currency.symbol%><%= number_with_precision(product["price"], precision: 2)%></span>
					<span>Grocer: <%= product["grocer"]%></span>
					<% if product["weight_in_grams"] != 0 %>
	                	<span>Weight in grams: <%= product["weight_in_grams"]%> grams</span>
	              	<% end %>
	              	<% if product["expiry_date"].to_date < (Date.today + 60.days)%>
                		<span>Expiry Date: <%= product["expiry_date"].to_date.to_formatted_s(:long_ordinal)%></span>
              		<% end %>
              		<span>Mode of Transport: <%= session[:delivery_method].capitalize%></span>
				</div>
				<div class="col-md-3 col-md-push-1">
					<span id="co_qty"><%= product["quantity"]%></span>
				</div>
				<div class="col-md-3 col-md-push-1">
					<% if product["tax_amount"].nil? %>
						<span id="co_qty">0.00</span>
					<% else %>
						<span id="co_qty"><%= number_with_precision((product["price"].to_f * product["quantity"].to_f) * (product["tax_amount"]/100), precision:2)%></span>
					<% end %>
				</div>
				<div class="col-md-3 col-md-push-1">
               		<%= @currency.symbol%><%= number_with_precision(product["price"].to_f * product["quantity"].to_f, precision: 2)%>
           	 	</div>
			</div>
		</li>
		<% end %>
	</ul>
	<div class="row">
		<h5 class="col-md-4" id="subtotal">Subtotal</h5>
		<span class="col-md-4 col-md-push-6"><%= @currency.symbol%><%= number_with_precision(@subtotal, precision: 2)%></span>
	</div>
	<div class="row">
		<h5 class="col-md-4" id="subtotal">Total Tax</h5>
		<span class="col-md-4 col-md-push-6"><%= @currency.symbol%><%= number_with_precision(@total_tax, precision: 2)%></span>
	</div>
	<div class="row">
      <h5 class="col-md-4" id="subtotal">ProjectMeal Order Request Fee</h5>
      <span class="col-md-4 col-md-push-6"><u><%= @currency.symbol%><%= number_with_precision(@fee, precision: 2)%></u></span>
    </div>
    <div class="row">
      <h4 class="col-md-4" id="subtotal">Total</h4>
      <span class="col-md-4 col-md-push-6"><%= @currency.symbol%><%= number_with_precision(@subtotal+@fee+@total_tax, precision: 2)%></span>
    </div>
    <div class="row buy col-md-4"> 
    	<%= form_tag trx_orders_stripe_path do%>
	        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	          data-key=<%= ENV["STRIPE_PUBLISHABLE_KEY"]%>
	          data-email=<%= current_org_person.email %>
	          data-description="Cart's total"
	          data-amount=<%=((@subtotal+@fee+@total_tax).round(2)*100).to_i%>
	          data-billingAddress="true"
	          data-shippingAddress="true">
	        </script>
	     <% end %>
    </div>
<% end %>

app/views/trx_orders/list_personal_purchases.html.erb
<% content_for(:sidebar) do %>
    <%= render :partial => "layouts/sidebar" %>
<% end %> 
<div class="col-md-10 col-md-offset-2 main">
  <% provide(:title, "Past Personal Purchases") %>
  <center><h1>Your Past Personal Purchases</h1></center>
  <%= render 'shared/error_messages' %>
  <div class="col-md-12 "> 
    <%= render :partial => "layouts/purchases" %>
  </div> 
</div>

app/views/trx_orders/list_purchases.html.erb
<% content_for(:sidebar) do %>
    <%= render :partial => "layouts/sidebar" %>
<% end %> 
<div class="col-md-10 col-md-offset-2 main">
	<% provide(:title, "Past Purchases") %>
	<center><h1>Company's Past Purchases</h1></center>
	<%= render 'shared/error_messages' %>
	<div class="col-md-12 "> 
    	<%= render :partial => "layouts/purchases" %>
  	</div> 
</div>

app/views/trx_orders/purchase_order.html.erb
<% content_for(:sidebar) do %>
    <%= render :partial => "layouts/sidebar" %>
<% end %> 
<div class="col-md-10 col-md-offset-2 main">
	<% provide(:title, "Purchase Order ##{@order.id}") %>
	<center><h1>Purchase Order #<%= @order[:id]%></h1></center>
	<hr>
	<%= render 'shared/error_messages' %>
	<div class="col-md-9 col-md-push-2" id="invoice-header">
	    <div class="col-md-4">
	      <i><u>Bill To</u></i>
	        <% if !@company.nil?%>
	          <b id="company"><%= @company.name %></b>
	        <% else %>
	          <b id="company"><%= current_org_person.first_name + " " + current_org_person.last_name %></b>
	        <% end %>
	    </div>
	    <% if @order.transport_method == 'delivery'%>
	      <div class="col-md-4 col-md-offset-3">
	        <i><u>Ship To</u></i>
	        <span><b>Name:</b> <%= @notification_params_name %></span>
	        <span><b>Address:</b> <%= @shipAddress[:address1]%></span>
	        <span><b>City:</b> <%= @shipAddress[:city]%></span>
	        <span><b>State:</b> <%= @shipAddress[:region]%></span>
	        <span><b>Postal Code:</b> <%= @shipAddress[:postal_code]%></span>
	        <span><b>Country:</b> <%= @shipAddress[:country]%></span>
	      </div>
	    <% else %>
	      <div class="col-md-4 col-md-offset-3">
	        <b><i><u>These items will be picked up at their respective stores</u></i></b>
	      </div>
	    <% end %>

	    <div class="col-md-11" id="invoice">
	      <%= render :partial => "layouts/invoicetables" %>
	      <%= link_to 'Open as PDF document', trx_orders_purchase_order_path(id: @order, :format => :pdf), :target => "_blank" %>
	    </div>
	</div>
</div>

app/views/trx_orders/purchase_order.pdf.erb
<%= wicked_pdf_stylesheet_link_tag "application" %>
<div class="col-md-12" id="invoice-header">
	<%= provide(:title, "Order Success") %>
	<center><h1>Purchase Order #<%= @order[:id]%></h1></center>
	<hr>

	<div class="col-md-3">
		<i><u>Sold To</u></i>
		<% if !@company.nil?%>
			<b id="company"><%= @company.name %></b>
		<% else %>
			<b id="company"><%= @contact.first_name + " " + @contact.last_name %></b>
		<% end %>
	</div>
	<div class="col-md-4 col-md-offset-3">
		<%if @order.transport_method == 'delivery'%>
			<i><u>Ship To</u></i>
			<span><b>Address:</b> <%= @shipAddress[:address1]%></span>
			<span><b>City:</b> <%= @shipAddress[:city]%></span>
			<span><b>Postal Code:</b> <%= @shipAddress[:postal_code]%></span>
			<span><b>Country:</b> <%= @shipAddress[:country]%></span>	
		<% else %>
			<b><i><u>These items will be picked up at their respective stores</u></i></b>
		<% end %>
	</div>
</div>

<div class="col-md-12 main" id="invoice">
	<%= render :partial => "layouts/invoicetables.html.erb" %>
</div>

app/views/trx_orders/stripe_success.html.erb
<div class="col-md-6 col-md-push-3" id="invoice-header">
	<%= provide(:title, "Order Success") %>
	<center><h1>Purchase Order #<%= @order[:id]%></h1></center>
  	<hr>

  	<div class="col-md-3">
		<i><u>Sold To</u></i>
		<% if !@company.nil?%>
			<b id="company"><%= @company.name %></b>
		<% else %>
			<b id="company"><%= current_org_person.first_name + " " + current_org_person.last_name %></b>
		<% end %>
	</div>
	<div class="col-md-4 col-md-offset-3">
		<%if @order.transport_method == 'delivery'%>
			<i><u>Ship To</u></i>
			<span><b>Address:</b> <%= @shipAddress[:address1]%></span>
			<span><b>City:</b> <%= @shipAddress[:city]%></span>
			<span><b>Postal Code:</b> <%= @shipAddress[:postal_code]%></span>
			<span><b>Country:</b> <%= @shipAddress[:country]%></span>
		<% else %>
			<b><i><u>These items will be picked up at their respective stores</u></i></b>
		<% end %>
	</div>
</div>

<div class="col-md-6 col-md-offset-3 main" id="invoice">
	<%= render :partial => "layouts/invoicetables" %>
	<div><%= link_to 'Open as PDF document', trx_orders_purchase_order_path(id: @order, :format => :pdf), :target => "_blank" %></div>
	<div><%= link_to "&laquo; Continue Shopping".html_safe , root_path %></div>
</div>