config/routes.rb
Rails.application.routes.draw do
  devise_for :org_people, :controllers => {
    :registrations => "org_people/registrations",
    :sessions => "org_people/sessions",
    :passwords => "org_people/passwords" ,
    :confirmations => "org_people/confirmations" }
  devise_scope :org_person do
    get 'signup',  to: 'org_people/registrations#new'
    get 'signin',  to: 'org_people/sessions#new'
    delete 'signout', to: 'org_people/sessions#destroy'
  end

  get 'catalogues/index'
  post 'carts/add/' => 'carts#add', :to => 'carts_add'
  post 'carts/add_delivery_method' => 'carts#add_delivery_method', :to => 'carts_add_delivery_method'

  get 'org_companies/:id/company_profile' => 'org_companies#company_profile', :as => 'org_companies_company_profile'
  get 'org_companies/people/' => 'org_companies#people', :to => "org_companies_people"
  get 'org_companies/list_deliverers/' => 'org_companies#list_deliverers', :to => "org_companies_list_deliverers"
  get 'org_companies/preferred_deliverers/' => 'org_companies#preferred_deliverers', :to => "org_companies_preferred_deliverers"
  post 'org_companies/ajax_add_deliverers/' => 'org_companies#ajax_add_deliverers', :to => "org_companies_ajax_add_deliverers"
  post 'org_companies/remove_preferred_deliverers/' => 'org_companies#remove_preferred_deliverers', :to => "org_companies_remove_preferred_deliverers"

  post 'org_products/delivery_status/' => 'org_products#delivery_status', :to => "org_products_delivery_status"
  post 'org_products/send_product_ready_email/' => 'org_products#send_product_ready_email', :to => "org_products_send_product_ready_email"
  post 'org_products/vote_product/' => 'org_products#vote_product', :to => "org_products_vote_product"
  get 'org_products/orders/' => 'org_products#orders', :to => "org_products_orders"
  get 'org_products/completed_orders/' => 'org_products#completed_orders', :to => "org_products_completed_orders"

  get 'org_people/stripe_settings/' => 'org_people#stripe_settings', :to => "org_people_stripe_settings"
  post 'org_people/stripe_update_settings/' => 'org_people#stripe_update_settings', :to => "org_people_stripe_update_settings"
  post 'org_people/edit_position/' => 'org_people#edit_position', :to => "org_people_edit_position"
  post 'org_people/remove_from_company/' => 'org_people#remove_from_company', :to => "org_people_remove_from_company"

  post 'trx_orders/stripe/' => 'trx_orders#stripe', :to =>"trx_orders_stripe"
  get 'trx_orders/stripe_success/:id' => 'trx_orders#stripe_success', :to => "trx_orders_stripe_success"
  get 'trx_orders/list_purchases/' => 'trx_orders#list_purchases', :to => "trx_orders_list_purchases"
  get 'trx_orders/list_personal_purchases/' => 'trx_orders#list_personal_purchases', :to => "trx_orders_list_personal_purchases"
  get 'trx_orders/purchase_order/' => 'trx_orders#purchase_order', :to => "trx_orders_purchase_order"


  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'
  
  post '/hooks/stripe' => 'hooks#stripe'


  post 'trx_orders/hook' => 'trx_orders#hook', :to => "trx_orders_hook"
  root "catalogues#index"

  resources :org_products
  resources :org_companies
  resources :org_people
  resources :trx_orders
  resources :carts
  resources :catalogues
  resources :sessions, only: [:new, :create, :destroy]


  match '/org_register', to:'org_companies#new', via: 'get'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_one :org_person
	belongs_to :org_product
	validates :name, presence: true
	validates :price, presence: true, numericality: true
	validates :grocer, presence: true
	validates :quantity, presence: true, numericality: true
	validates :weight_in_grams, presence: true, numericality: true
	validates :expiry_date, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	# Shows all the items client has ordered in the shopping cart
	def index
		@org_products = Array.new
		@currency = Money.new(1, session[:currency]["iso_code"]).currency
		# If the session delivery method is nil, default to pickup
		if session[:delivery_method].nil?
			session[:delivery_method] = 'pickup'
		end
		# Search to see if this user already have existing items to checkout in the db
		if current_org_person
			session_to_cart = session[:cart] # Let's check our session to see if the user carted anything while not signed in.
			if !session_to_cart.nil? # If they did
				session_to_cart.each do |c| # Create each item in the session cart in the DB and attach to current user.
					if cart = Cart.find_by(org_person_id: current_org_person.id, org_product_id: c[1]["id"]) # Check if the item exists in DB
						cart.update(org_person_id: current_org_person.id, # If it did, update it
									org_product_id: c[1]["id"],
									name: c[1]["title"], 
									tax_amount: c[1]["tax_amount"],
			                      	price: c[1]["price"].to_f, 
			                      	grocer: c[1]["grocer"],
			                      	quantity: c[1]["quantity"],
			                      	weight_in_grams: c[1]["weight"],
			                      	expiry_date: c[1]["expiry"])
					else # else create it	
						Cart.create(org_person_id: current_org_person.id,
			                      org_product_id: c[1]["id"], 
			                      name: c[1]["title"], 
			                      tax_amount: c[1]["tax_amount"],
			                      price: c[1]["price"].to_f, 
			                      grocer: c[1]["grocer"],
			                      quantity: c[1]["quantity"],
			                      weight_in_grams: c[1]["weight"],
			                      expiry_date: c[1]["expiry"])
					end	
				end
			end
			session[:cart] = nil
			@products = Cart.where(org_person_id: current_org_person.id)
		else
			@products = session[:cart]
		end

		if @products == nil
		else
			@products.to_a.each do |product|
				if current_org_person
					@productRecord = product.org_product # products are from cart.
				else # we got cart data from a session
					@productRecord = OrgProduct.find_by_id(product[0])
				end
				if @productRecord # The products are from session, check if the item is in the db
					expiry = @productRecord.expiry_date.to_date.to_formatted_s(:long_ordinal) # Get its expiry
					available_quantity = @productRecord.available_quantity # Get its quantity
					if available_quantity.to_i > 0 && Time.now < expiry	# If it's not expired, or quantity > 0
						@org_products << [@productRecord, product] # We can show it
					else 
						@org_products << [@productRecord, product] #This should not be here?
						if current_org_person #It was cart DB data
							Cart.destroy(product.id) # Delete the item from the Cart DB attached to the user
						else
							session[:cart].delete(p["id"]) # Delete the item from the session
						end
					end
				end 
			end
		end
	end

	def add
		# cart_item – try to find the item in the db if it exists
		if current_org_person
			cart_item = Cart.find_by(org_person_id: current_org_person.id, org_product_id: params[:product_id])
		end
		# It doesn't exist, and the user is logged on, create it for this user in the db.
		if cart_item.blank? && current_org_person
			cart_item = Cart.create(org_person_id: current_org_person.id,
									org_product_id: params[:product_id], 
									name: params[:title],
									tax_amount: params[:tax],
									price: params[:price], 
									grocer: params[:grocer],
									quantity: params[:quantity],
									weight_in_grams: params[:weight],
									expiry_date: params[:expiry])
		# It exists, and user is logged on, update it in the db.
		elsif cart_item && current_org_person
			cart_item.update(name: params[:title], 
							tax_amount: params[:tax],
							price: params[:price], 
							grocer: params[:grocer],
							quantity: params[:quantity],
							weight_in_grams: params[:weight],
							expiry_date: params[:expiry])
		# The user is not logged on, so we use sessions
		else
			session[:cart] ||={}
			session[:cart][params[:product_id]] = {id: params[:product_id],
												title: params[:title],
												tax_amount: params[:tax],
												price: params[:price], 
												grocer: params[:grocer],
												quantity: params[:quantity],
												weight: params[:weight],
												expiry: params[:expiry]

			}
		end
		render nothing:true
	end

	def add_delivery_method
		session[:delivery_method] = nil
		session[:delivery_method] = params[:deliveryMode]
		render nothing:true 
	end

	def destroy
		# Delete the item from the cart
		if current_org_person
			Cart.destroy(params[:id])
		else
			session[:cart].delete(params[:id])
		end
		redirect_to carts_path # Redirect to the shopping cart
	end
end

app/views/carts/index.html.erb
<div class="col-md-9 col-md-offset-2 main">
  <%= provide(:title, "Shopping Cart") %>
	<% if @org_products.empty? %>
		<center><h1>There are no items in your cart</h1></center>
	<% else %>
		<center><h1>Items in your cart</h1></center>
		<ul class="catalogue">
			<% @org_products.each do |product| %>
			<li>
				<% if product[0].available_quantity > 0 && Time.now < product[0].expiry_date.to_date.to_formatted_s(:long_ordinal) %>
					<div class="row">
						<div class="col-md-2 prodImage">
							<% if !product[0].image.blank? %>
			                  <%= image_tag product[0].image_url(:medium).to_s, :class =>"displayImage"%>  
			                <% else %>  
			                  <div class="displayImage">
			                    <i class="fa fa-question-circle photoUpload"></i>
			                    <p>Picture Unavailable</p>
			                  </div>
			                <% end %>
						</div>
						<div class="col-md-7" id="prodInfo">
				<% else %>
					<div class="row unavailable-product">
						<div class="col-md-4">
				<% end %>

							<h4 id="title"><%= link_to product[0].name, product[0] %></h4>
							<span><%= hidden_field_tag 'id', product[0].id%></span>
		                	<span><%= hidden_field_tag 'tax', product[0].tax_amount%></span>
		                	<div class="price">Price: <%= @currency.symbol %><span><%= number_with_precision(product[0].price, precision: 2) %></span></div>
		                	<div class="grocer">Grocer: <span><%= product[0].org_company.name%></span></div>
		                	<% if product[0].weight_in_grams != 0 %>
			                  <div id="wig">Grams Per Item: <span><%= product[0].weight_in_grams %></span> grams or <%= number_with_precision((product[0].weight_in_grams/1000.00), precision: 2)%> kg</div>
			                <% else %>
			                  <div id="wig" class="hidden">Grams Per Item: <span><%= product[0].weight_in_grams %></span> grams</div>
			                <% end %>
			                <% if product[0].available_quantity > 150 %>
			                  <div id="aq" class="hidden">Approx. Available Quantity: <span><%= product[0].available_quantity %></span></div>
			                <% else %>
			                  <div id="aq">Approx. Available Quantity: <span><%= product[0].available_quantity %></span></div>
			                <% end %>
			                <% if product[0].expiry_date.to_date < (Date.today + 60.days)%>
			                  <div class="expiry">Expiry Date: <i><%= product[0].expiry_date.to_date.to_formatted_s(:long_ordinal) %></i></div>
			                <% else %>
			                  <div class="expiry hidden">Expiry Date: <i><%= product[0].expiry_date.to_date.to_formatted_s(:long_ordinal) %></i></div>
			                <% end %>
	               		</div>
	               		<% if product[0].available_quantity > 0 && Time.now < product[0].expiry_date.to_date.to_formatted_s(:long_ordinal) %>
	               			<div class="col-sm-3 quantity-box">
	               				<!-- Make sure the quantity is smaller or as big as available quantity -->
	               				<div class="input-group">
	               					<% if current_org_person %>
	               						<input id="quantity" name="quantity" type="text" class="form-control" placeholder="Edit Quantity." value=<%= product[1].quantity%> />
	               					<% else %> 
                      					<input id="quantity" name="quantity" type="text" class="form-control" placeholder="Edit Quantity." value=<%= session[:cart][product[0][:id].to_s]["quantity"]%> />
                      				<% end %>
                      				<span class="input-group-btn">
                      					<button class="btn btn-success addedPopup" data-toggle="modal" data-target="#addedPopup-modal<%= product[0].id%>" type="submit">
                      					Edit
                      					</button>
                      					<% if current_org_person %>
                      						<button type="button" class="btn btn-danger remove" id="deleteProductFromSession"> <%= link_to "Delete", cart_path(product[1].id), method: :delete, data: { confirm: "You really want to delete "+product[1].name+" from your cart?"} %>
                      					<% else %>
                      						<button type="button" class="btn btn-danger remove" id="deleteProductFromSession"> <%= link_to "Delete", cart_path(product[0].id), method: :delete, data: { confirm: "You really want to delete "+product[0].name+" from your cart?"} %>
                      					<% end %>
                      					</button>
                      				</span>
                      			</div>  

                      			<!-- Modal -->
                      			<div class="modal fade addProdModal" id="addedPopup-modal<%= product[0].id%>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
				                    <div class="modal-dialog">
				                      <div class="modal-content">
				                        <div class="modal-header">
				                          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				                          <h4 class="modal-title">Success!</h4>
				                        </div>
				                        <div class="modal-body">
				                          <p id="modal-message"></p>
				                        </div>  
				                    </div>
				                </div>
				            </div>
				        <% else %>
				        	<div class="col-sm-6 not-available">
			                  <h3>This item is no longer available.</h3>
			                </div>
	               		<% end %>
	               	</div>
			</li>
			<% end %>
		</ul>
		<div class="delivery_options radios">
			<% if session[:delivery_method] == 'delivery' %>
				<label>
		            <input type="radio" name="deliveryRadios" id="pickup" value="pickup">
		            Pickup
		        </label>
		          	<label>
		            <input type="radio" name="deliveryRadios" id="delivery" value="delivery" checked>
		            Delivery
		        </label>
		    <% else %>
		    	<label>
		            <input type="radio" name="deliveryRadios" id="pickup" value="pickup" checked>
		            Pickup
		        </label>
          		<label>
            		<input type="radio" name="deliveryRadios" id="delivery" value="delivery">
            		Delivery
          		</label>
			<% end %>
		</div>
		<div class="checkout">
			<button type="button" class="btn btn-success checkouts">
				<%= link_to "Proceed To Checkout", trx_orders_path %>
			</button>
		</div>
	<% end %>
</div>