config/routes.rb
Rails.application.routes.draw do
  devise_for :org_people, :controllers => {
    :registrations => "org_people/registrations",
    :sessions => "org_people/sessions",
    :passwords => "org_people/passwords" ,
    :confirmations => "org_people/confirmations" }
  devise_scope :org_person do
    get 'signup',  to: 'org_people/registrations#new'
    get 'signin',  to: 'org_people/sessions#new'
    delete 'signout', to: 'org_people/sessions#destroy'
  end

  get 'catalogues/index'
  post 'carts/add/' => 'carts#add', :to => 'carts_add'
  post 'carts/add_delivery_method' => 'carts#add_delivery_method', :to => 'carts_add_delivery_method'

  get 'org_companies/:id/company_profile' => 'org_companies#company_profile', :as => 'org_companies_company_profile'
  get 'org_companies/people/' => 'org_companies#people', :to => "org_companies_people"
  get 'org_companies/list_deliverers/' => 'org_companies#list_deliverers', :to => "org_companies_list_deliverers"
  get 'org_companies/preferred_deliverers/' => 'org_companies#preferred_deliverers', :to => "org_companies_preferred_deliverers"
  post 'org_companies/ajax_add_deliverers/' => 'org_companies#ajax_add_deliverers', :to => "org_companies_ajax_add_deliverers"
  post 'org_companies/remove_preferred_deliverers/' => 'org_companies#remove_preferred_deliverers', :to => "org_companies_remove_preferred_deliverers"

  post 'org_products/delivery_status/' => 'org_products#delivery_status', :to => "org_products_delivery_status"
  post 'org_products/send_product_ready_email/' => 'org_products#send_product_ready_email', :to => "org_products_send_product_ready_email"
  post 'org_products/vote_product/' => 'org_products#vote_product', :to => "org_products_vote_product"
  get 'org_products/orders/' => 'org_products#orders', :to => "org_products_orders"
  get 'org_products/completed_orders/' => 'org_products#completed_orders', :to => "org_products_completed_orders"

  get 'org_people/stripe_settings/' => 'org_people#stripe_settings', :to => "org_people_stripe_settings"
  post 'org_people/stripe_update_settings/' => 'org_people#stripe_update_settings', :to => "org_people_stripe_update_settings"
  post 'org_people/edit_position/' => 'org_people#edit_position', :to => "org_people_edit_position"
  post 'org_people/remove_from_company/' => 'org_people#remove_from_company', :to => "org_people_remove_from_company"

  post 'trx_orders/stripe/' => 'trx_orders#stripe', :to =>"trx_orders_stripe"
  get 'trx_orders/stripe_success/:id' => 'trx_orders#stripe_success', :to => "trx_orders_stripe_success"
  get 'trx_orders/list_purchases/' => 'trx_orders#list_purchases', :to => "trx_orders_list_purchases"
  get 'trx_orders/list_personal_purchases/' => 'trx_orders#list_personal_purchases', :to => "trx_orders_list_personal_purchases"
  get 'trx_orders/purchase_order/' => 'trx_orders#purchase_order', :to => "trx_orders_purchase_order"


  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'
  
  post '/hooks/stripe' => 'hooks#stripe'


  post 'trx_orders/hook' => 'trx_orders#hook', :to => "trx_orders_hook"
  root "catalogues#index"

  resources :org_products
  resources :org_companies
  resources :org_people
  resources :trx_orders
  resources :carts
  resources :catalogues
  resources :sessions, only: [:new, :create, :destroy]


  match '/org_register', to:'org_companies#new', via: 'get'
end

app/controllers/catalogues_controller.rb
class CataloguesController < ApplicationController
  def index
  	# If search is not empty
    
  	if(current_org_person && @contact = OrgContact.find_by(org_person_id: current_org_person.id))
  		@country = TypCountry.find_by_id(@contact['typ_country_id'])
  		@currency = Money.new(1, @country.currency_code).currency
  		session[:currency] = @currency
  		@latitude = @contact["latitude"]
  		@longitude = @contact["longitude"]
  	else
      # If the user had visited before and have geolocation saved in their cookies, use that
      if !cookies[:geolocation].nil?
        @location = JSON.parse(cookies[:geolocation]).symbolize_keys
      else
        # Geolocate the user by IP Address and use the default currency
    		@ip = request.remote_ip
        if Rails.env.production?
          locale = request.location
          @location = {longitude: locale.longitude, latitude: locale.latitude, country_code: locale.country_code}
        else
          @location = GeoIp.geolocation("24.84.225.124")
        end
      end

  		@longitude = @location[:longitude]
  		@latitude = @location[:latitude]
  		@country_code = @location[:country_code]
  		@country = TypCountry.find_by_iso(@country_code)
  		@currency = Money.new(1, @country.currency_code).currency
  		session[:currency] = @currency
      cookies[:geolocation] = {value: JSON.generate(@location), expires: Time.now + 3600 * 24 * 7} # Set cookie for a week
      # If you get an undefined data error, chances are, the internet is too slow
      # Change the timeout in geocoder.rb to more than 240 secs    
  	end
  	if params[:search]
	  	@query = OrgProduct.search(params[:search], 
        where: {
          location: {near: [@latitude, @longitude], within: "100km"},
          expiry_date: {gt: Time.now},
          available_quantity: {gt: 0}
          }, 
        page: params[:page], per_page:20)
	  	@org_products = @query.results # Assign results to @org_products
      if current_org_person
        # Let's check if the user did anything offline and filled up their session cart
        @cart = session[:cart]
        if !@cart.nil? # If there was something in the session
          @cart.each do |c| # Create each item in the session cart in the DB and attach to current user.
            Cart.create(org_person_id: current_org_person.id,
                      org_product_id: c[1]["id"], 
                      name: c[1]["title"], 
                      tax_amount: c[1]["tax_amount"],
                      price: c[1]["price"].to_f, 
                      grocer: c[1]["grocer"],
                      quantity: c[1]["quantity"],
                      weight_in_grams: c[1]["weight"],
                      expiry_date: c[1]["expiry"])
          end 
        end
        @cart = Cart.where(org_person_id: current_org_person.id) #Now retrieve all their items
        @cart = @cart.to_a
        session[:cart] = nil # Clean out the session cart
      else # No registered user, start with a session.
        @cart ||= session[:cart] 
        if @cart.nil? # This makes sure that @cart is a hash no matter what
          @cart = Hash.new # The template needs a hash or it'll throw an error.
        end
      end
	  	
      if @org_products.empty?
	  		flash.now[:danger] = 'There were no results from your search. Please try again'
	  	end
  	else
  		@org_products = {} # Search was empty. Give nothing
  	end
  end
end

app/views/catalogues/index.html.erb
<div class="col-md-6 col-md-push-3 form-margins">
  <%= provide(:title, "Search")%>
  <center><h1>Search For Food or Grocer</h1></center>
  <%= form_tag root_path, :class => "input-group", :method => :get do %>
    <%= text_field_tag :search, params[:search], :class => "form-control" %>
    <span class="input-group-btn">
      <%= submit_tag "Search", :name => nil, :class => "btn btn-default" %>
    </span>
  <% end %>
</div>

<div class="col-md-10 col-md-offset-1 main">
  <% if @org_products.empty? %>
  <% else %> 
    <%= will_paginate @query, renderer: BootstrapPagination::Rails %>
      <ul class="catalogue">
        <% @org_products.each do |product| %>
        <li>
          <div class="row">
            <div class="col-md-2 prodImage">
              <% if !product["image"].blank? %>
                <%= image_tag product.image_url(:medium).to_s, :class => "displayImage"%>
              <% else %>
                <div class="displayImage">
                  <i class="fa fa-question-circle photoUpload"></i>
                  <p>Picture Unavailable</p>
                </div>
              <% end %>
            </div>
            <div class="col-md-8" id="prodInfo">
              <h4 id="title"><%= link_to product.name, product %></h4>
              <span><%= hidden_field_tag 'id', product.id %></span>
              <span><%= hidden_field_tag 'tax', product.tax_amount %></span>
              <div class="price">Price: <%= @currency.symbol %><span><%= number_with_precision(product.price, precision: 2)%></span></div>
              <div class="grocer">Grocer: <span><%= link_to product.org_company.name, org_companies_company_profile_path(product.org_company.id)%></span></div>
              <% if product.weight_in_grams != 0%>
                <div id="wig">Grams Per Item: <span><%= product.weight_in_grams %></span> grams or <%= number_with_precision((product.weight_in_grams/1000.00), precision: 2)%> kg</div>
              <% else %>
                <div id="wig" class="hidden">Grams Per Item: <span><%= product.weight_in_grams %></span> grams</div>
              <% end %>
              <% if product.available_quantity > 150 %>
                <div id="aq" class="hidden">Approx. Available Quantity: <span><%= product.available_quantity %></span></div>
              <% else %>
                <div id="aq">Approx. Available Quantity: <span><%= product.available_quantity %></span></div>
              <% end %>
              <% if product.expiry_date.to_date < (Date.today + 60.days) %>
                <div class="expiry">Expiry Date: <i><%= product.expiry_date.to_date.to_formatted_s(:long_ordinal) %></i></div>
              <% else %>
                <div class="expiry hidden">Expiry Date: <i><%= product.expiry_date.to_date.to_formatted_s(:long_ordinal) %></i></div>
              <% end %>
            </div>
            <% if product.online_order_available == true %>
              <div class="col-md-2 quantity-box">
                <%= render :partial => "layouts/additem", locals: {product: product, page: "catalogue_index"}%>
              </div>
            <% end %>
            <% if current_org_person %>
              <% if product.online_order_available == true %>
                <div class="btn-group col-sm-9 col-md-offset-2 vote-buttons">
                  <%= render :partial => "layouts/votebuttons", locals: {product: product} %>
              <% else %>
                <div class="btn-group col-sm-2 quantity-box">
                  <div class="btn-group col-sm-9 col-md-offset-2 vote-buttons">
                    <%= render :partial => "layouts/votebuttons", locals: {product: product} %>
                  </div>
              <% end %>
              </div>
            <% end %>
          </div>
        </li>
        <% end %>
      </ul>
      <%= will_paginate @query, renderer: BootstrapPagination::Rails %>
  <% end %>
</div>