config/routes.rb
Rails.application.routes.draw do
  devise_for :org_people, :controllers => {
    :registrations => "org_people/registrations",
    :sessions => "org_people/sessions",
    :passwords => "org_people/passwords" ,
    :confirmations => "org_people/confirmations" }
  devise_scope :org_person do
    get 'signup',  to: 'org_people/registrations#new'
    get 'signin',  to: 'org_people/sessions#new'
    delete 'signout', to: 'org_people/sessions#destroy'
  end

  get 'catalogues/index'
  post 'carts/add/' => 'carts#add', :to => 'carts_add'
  post 'carts/add_delivery_method' => 'carts#add_delivery_method', :to => 'carts_add_delivery_method'

  get 'org_companies/:id/company_profile' => 'org_companies#company_profile', :as => 'org_companies_company_profile'
  get 'org_companies/people/' => 'org_companies#people', :to => "org_companies_people"
  get 'org_companies/list_deliverers/' => 'org_companies#list_deliverers', :to => "org_companies_list_deliverers"
  get 'org_companies/preferred_deliverers/' => 'org_companies#preferred_deliverers', :to => "org_companies_preferred_deliverers"
  post 'org_companies/ajax_add_deliverers/' => 'org_companies#ajax_add_deliverers', :to => "org_companies_ajax_add_deliverers"
  post 'org_companies/remove_preferred_deliverers/' => 'org_companies#remove_preferred_deliverers', :to => "org_companies_remove_preferred_deliverers"

  post 'org_products/delivery_status/' => 'org_products#delivery_status', :to => "org_products_delivery_status"
  post 'org_products/send_product_ready_email/' => 'org_products#send_product_ready_email', :to => "org_products_send_product_ready_email"
  post 'org_products/vote_product/' => 'org_products#vote_product', :to => "org_products_vote_product"
  get 'org_products/orders/' => 'org_products#orders', :to => "org_products_orders"
  get 'org_products/completed_orders/' => 'org_products#completed_orders', :to => "org_products_completed_orders"

  get 'org_people/stripe_settings/' => 'org_people#stripe_settings', :to => "org_people_stripe_settings"
  post 'org_people/stripe_update_settings/' => 'org_people#stripe_update_settings', :to => "org_people_stripe_update_settings"
  post 'org_people/edit_position/' => 'org_people#edit_position', :to => "org_people_edit_position"
  post 'org_people/remove_from_company/' => 'org_people#remove_from_company', :to => "org_people_remove_from_company"

  post 'trx_orders/stripe/' => 'trx_orders#stripe', :to =>"trx_orders_stripe"
  get 'trx_orders/stripe_success/:id' => 'trx_orders#stripe_success', :to => "trx_orders_stripe_success"
  get 'trx_orders/list_purchases/' => 'trx_orders#list_purchases', :to => "trx_orders_list_purchases"
  get 'trx_orders/list_personal_purchases/' => 'trx_orders#list_personal_purchases', :to => "trx_orders_list_personal_purchases"
  get 'trx_orders/purchase_order/' => 'trx_orders#purchase_order', :to => "trx_orders_purchase_order"


  post '/connect/managed' => 'stripe#managed', as: 'stripe_managed'
  
  post '/hooks/stripe' => 'hooks#stripe'


  post 'trx_orders/hook' => 'trx_orders#hook', :to => "trx_orders_hook"
  root "catalogues#index"

  resources :org_products
  resources :org_companies
  resources :org_people
  resources :trx_orders
  resources :carts
  resources :catalogues
  resources :sessions, only: [:new, :create, :destroy]


  match '/org_register', to:'org_companies#new', via: 'get'
end

app/views/layouts/_additem.html.erb
<div class="input-group">
	<% if current_org_person %>
		<% if page == "org_products_show"%>
			<input id="quantity" name="quantity" type="text" class="form-control" placeholder="Enter Quantity" value=<%= @cart[0].try(:quantity) %>>
		<% elsif @cart.select{ |cart| cart["org_product_id"] == product.id}[0].try(:quantity) && page == "catalogue_index" %>
			<input id="quantity" name="quantity" type="text" class="form-control" placeholder="Enter Quantity" value=<%= @cart.select{|cart| cart["org_product_id"] == product.id}[0].try(:quantity) %> >
		<% else %>
			<input id="quantity" name="quantity" type="text" class="form-control"  placeholder="Enter Quantity" />
		<% end %>
	<% else %>
		<% if @cart[product.id.to_s] %>
			<input id="quantity" name="quantity" type="text" class="form-control" placeholder="Enter Quantity" value=<%= @cart[product.id.to_s]["quantity"]%> />
		<% else %>
			<input id="quantity" name="quantity" type="text" class="form-control"  placeholder="Enter Quantity" />
		<% end %>
	<% end %>

	<span class="input-group-btn">
		<button class="btn btn-success addedPopup" data-toggle="modal" data-target="#addedPopup-modal<%=product.id%>" type="submit" >
			Add
		</button>
	</span>
</div>

<!-- Modal -->
<div class="modal fade addProdModal" id="addedPopup-modal<%= product.id%>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Success!</h4>
      </div>
      <div class="modal-body">
        <p id="modal-message"></p>
      </div>  
  </div>
</div>

app/views/layouts/_companyfields.html.erb
<%= f.fields_for :org_contacts do |contact|%>
	<%= contact.text_field :address1, placeholder: "Address 1", :class => "form-control" %>
	<%= contact.text_field :address2, placeholder: "Address 2", :class => "form-control" %>
	<%= contact.text_field :city, placeholder: "City", :class => "form-control" %>
	<%= contact.fields_for :typ_countries do |country|%>
      <%= country.collection_select :id, TypCountry.order(:country),:id,:country, {prompt: "Please Select Country", selected: @contactInfo["typ_country_id"] }, {:class => "form-control"} %>
    <% end %>
    <%= contact.fields_for :typ_regions do |region|%>
      <%= region.grouped_collection_select :id, TypCountry.order(:country),:typ_region, :country, :id, :name, {prompt: "Please Select Region", selected: @contactInfo["typ_region_id"] }, {:class => "form-control"}%>
    <% end %>
    <%= contact.text_field :postal_code, placeholder: "Postal Code", :class => "form-control" %>
	<%= contact.text_field :business_number, placeholder: "Business Number", :class => "form-control" %>
	<%= contact.text_field :cell_number, placeholder: "Cell Number", :class => "form-control" %>
	<%= contact.hidden_field :email, value: current_org_person.email %>
<% end %>

app/views/layouts/_contactfields.html.erb
<%= f.fields_for :org_contacts do |contact|%>
  
  <% if !@contactInfo["avatar"].blank? %>
    <%= image_tag @contactInfo.avatar_url(:medium).to_s, :class=>"profilePhoto" %>
  <% end %>
  <div class="photoPreview">
    <i class="fa fa-upload photoUpload"></i>
    <p id="uploadClick">Click to Upload</p>
  </div>
    
  <%= contact.file_field :avatar, accept: 'image/png,image/gif,image/jpeg, image/jpg', id: 'uploadAvatar' %>
  <p class="deletePhoto">Delete</p>

	<%= contact.text_field :address1, placeholder: "Address 1", :class => "form-control" %>
	<%= contact.text_field :address2, placeholder: "Address 2", :class => "form-control" %>
	<%= contact.text_field :city, placeholder: "City", :class => "form-control" %>
    <%= contact.fields_for :typ_countries do |country|%>
      <%= country.collection_select :id, TypCountry.order(:country),:id,:country, {prompt: "Please Select Country", selected: @contactInfo["typ_country_id"] }, {:class => "form-control"} %>
    <% end %>
    <%= contact.fields_for :typ_regions do |region|%>
      <%= region.grouped_collection_select :id, TypCountry.order(:country),:typ_region, :country, :id, :name, {prompt: "Please Select Region", selected: @contactInfo["typ_region_id"] }, {:class => "form-control"}%>
    <% end %>
    <%= contact.fields_for :org_company do |company|%>
      <%= company.collection_select :id, OrgCompany.order(:name),:id,:name, {prompt: "Please Select Company", selected: @contactInfo["org_company_id"] }, {:class => "form-control"} %>
    <% end %>
	<%= contact.text_field :postal_code, placeholder: "Postal Code", :class => "form-control" %>
	<%= contact.text_field :email, placeholder: "Email", :class => "form-control", readonly: true %>
	<%= contact.text_field :business_number, placeholder: "Business Number", :class => "form-control" %>
	<%= contact.text_field :cell_number, placeholder: "Cell Number", :class => "form-control" %>
	<%= contact.hidden_field :org_person_id, value: current_org_person.id %>
<% end %>

app/views/layouts/_footer.html.erb
<div id="push"></div>
<footer class="footer navbar-fixed-bottom">
	<div class="container">
		<nav>
			<ul>
				
	      		<li><%= link_to "Contact Us", "#" %></li>
	      		<li><%= link_to "Terms of Use",   "#" %></li>
	      		<li><%= link_to "Privacy Policy",   "#" %></li>
	      		<li><%= link_to "How it Works?",   "#" %></li>
			</ul>
		</nav>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <div class="navbar-header">
        <span><%= link_to "ProjectMeal", root_path, id: "logo" %></span>
        <span class="beta">Beta</span>
        <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <nav class="navbar-collapse bs-navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Shopping Cart", carts_path %></li>
          <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account <b class="caret"></b></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Profile", edit_org_person_path(current_org_person.id) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", destroy_org_person_session_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_invoicetables.html.erb
<table class="table table-bordered">
	<tr>
		<th>From Grocer</th>
		<th>Item</th>
		<th>Quantity</th>
		<th>Total</th>
	</tr>
	<% @purchase_items.each_with_index do |item, index|%>
		<tr>
			<td><%= item.OrgProduct.org_company.name%></td>
			<td><%= item[:name]%></td>
			<td><%= item[:quantity]%></td>
			<td><%= @currency.symbol%><%= number_with_precision(item[:price].to_f * item[:quantity].to_f, precision:2)%></td>
			<br>
		</tr>
	<% end %>
	<tr>
		<td colspan="3">ProjectMeal Fee:</td>
		<td><%= @currency.symbol%><%= number_with_precision(@pm_fee.fee_amount, precision: 2)%></td>
	</tr>
	<tr>
		<td colspan="3">Total Taxes:</td>
		<td><%= @currency.symbol%><%= number_with_precision(@total_tax, precision: 2)%></td>
	</tr>
	<tr>
		<td colspan="3">Total Cost:</td>
		<td><%= @currency.symbol%><%= number_with_precision(@order.total_amount/100, precision:2)%></td>
	</tr>
</table>

<div>
	<i><u>Contact Details</u></i>
	<span><b>Full name:</b> <%= @notification_params_name %></span> 
	<span><b>Email:</b> <%= @shipAddress.email%></span> 
	<span><b>Telephone:</b> <%= @shipAddress.telephone == true ? @shipAddress.telephone : "N/A"%></span> 
</div>

<div>
	<i><u>Payment Details</u></i>
	<span><b>Payment status:</b> Complete</span> 
	<span><b>Payment date:</b> <%= @order.purchased_at%></span> 
</div>

app/views/layouts/_preferreddeliverers.html.erb
<% if @preferred_deliverers.count > 0 %>
	<ul class="pref_deliverers">
		<% @preferred_deliverers.each do |deliverer| %>
		<li>
			<div class="col-md-9">
				<div><b><%= deliverer[0].name.to_s %></b></div>
				<div><%= hidden_field_tag 'id', deliverer[0].id.to_i%></div>
				<div><%= deliverer[1].address1.to_s%></div>
				<div><%= deliverer[1].city.to_s%>, <%= deliverer[2].name%>, <%= deliverer[1].postal_code%></div>
				<div><%= deliverer[3].country%></div>
			</div>

			<div class="col-sm-3 deliverer-box">
				<%= button_to "Remove Deliverer", {action: "remove_preferred_deliverers", method: "post", deliverer_id: deliverer[0].id}, {class: "btn btn-danger removeDeliverer", data: {toggle: "modal", target: "#removeDeliverer-modal#{deliverer[0].id.to_i}", deliverer_id: deliverer[0].id, type: "json"}, type: "submit", remote: true}%>
				<!-- Modal -->
		        <div class="modal fade removeDeliverModal" id="removeDeliverer-modal<%= deliverer[0].id.to_i%>" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
		            <div class="modal-dialog">
		              <div class="modal-content">
		                <div class="modal-header">
		                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		                  <h5>Remove <%= deliverer[0].name%> from your Preferred Deliverers</h5>
		                </div>
		                <div class="modal-body">
		                  Are you sure?
		                </div>
		                <div class="modal-footer">
		                  <button type="button" data-dismiss="modal" class="btn btn-primary" id="delete">Remove</button>
		                  <button type="button" data-dismiss="modal" class="btn">Cancel</button>
		                </div>  
		            </div>
		          </div>
				</div>
			</div>
		</li>
		<% end %>
	</ul>
<% else %>
	<center><h4>You have no preferred deliverers</h4></center> 
<% end %>

app/views/layouts/_productfields.html.erb
<% if !@product["image"].blank? %>
	<%= image_tag @product.image_url(:medium).to_s, :class=>"imagePhoto" %>
<% end %>
<div class="imagePreview">
	<i class="fa fa-upload imageUpload"></i>
	<p id="uploadClick">Click to Upload</p>
</div>

<%= f.file_field :image, accept: 'image/png,image/gif,image/jpeg, image/jpg', id: 'uploadImage' %>
<p class="deleteFoodImage">Delete</p>

<%= f.text_field :name, placeholder: "Product Name", :class => "form-control" %>
<%= f.fields_for :typ_category do |category|%>
<%= category.collection_select :id, TypCategory.order(:name),:id,:name, {prompt: "Please Select Category", selected: @product["typ_category_id"] }, {:class => "form-control"} %>
<% end %>
<%= f.fields_for :typ_subcategory do |subcategory|%>
<%= subcategory.grouped_collection_select :id, TypCategory.order(:name),:typ_subcategory, :name, :id, :name, {prompt: "Please Select Subcategory", selected: @product["typ_subcategory_id"] }, {:class => "form-control"}%>
<% end %>
<%= f.text_field :price, placeholder: "Price", :class => "form-control", :value => (number_with_precision(@product.price, :precision => 2)) %>
<%= f.text_field :weight_in_grams, placeholder: "Weight in grams", :class => "form-control" %>
<%= f.text_field :available_quantity, placeholder: "Available Quantity", :class => "form-control" %>
<%= f.date_field :expiry_date, placeholder: "Expiration Date", :class => "form-control expiry_field" %>
<%= f.text_area :description, placeholder: "Description", :class => "form-control" %>
<div class="order-online-radios">
	<span>Will customers be able to order this product online?</span>
	<%= f.radio_button :online_order_available, true %> Yes
	<%= f.radio_button :online_order_available, false %> No
</div>
<div class="order-online-radios">
	<span>Choose the tax option that applies for your product:</span>
	<% @tax_details.each do |t| %>
		<span><%= f.radio_button :tax_amount, t[1] %> <%= t[0]%> (<%= number_to_percentage(t[1], strip_insignificant_zeros:true)%>)</span>
	<% end %>	
</div>

app/views/layouts/_purchases.html.erb
<table class="table">
	<% if !@purchases.empty?%>
		<thead>
			<tr>
				<th>Order ID</th>
		        <th>Ship To</th>
		        <th>Purchase Date</th>
		        <th>Total</th>
			</tr>
		</thead>
		<tbody>
			<% @purchases.each do |purchase| %>
				<tr>
					<td><%= link_to purchase[:id], trx_orders_purchase_order_path(id: purchase[:id]) %></td>
					<td>
						<span class="list_purchases_shipaddress">
							<div><%= purchase.ship_to_contact.first_name%></div>
            				<div><%= purchase.ship_to_contact.address1%></div>
            				<div>
            					<%= purchase.ship_to_contact.city%>,
              					<%= purchase.ship_to_contact.region%>,
              					<%= purchase.ship_to_contact.postal_code%>
            				</div>
            				<div>
            					<%= purchase.ship_to_contact.country%>
            				</div>
						</span>
					</td>
					<td><%= purchase[:purchased_at].to_date.to_formatted_s(:long_ordinal)%></td>
					<td><%= @currency.symbol%><%= number_with_precision((purchase[:total_amount]/100).to_f, precision: 2)%></td>
				</tr>
			<% end %>
		</tbody>
	<% else %>
		<center><h4>There has been no purchases made so far.</h4></center>
	<% end %>
</table>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<% if signed_in? %>
<div class="col-sm-3 col-md-2 sidebar">
	<ul class="nav nav-sidebar">
	    <li class="sidebar_overview"><%= link_to "Overview", edit_org_person_path(current_org_person) %></li>
	    <% if current_org_person != nil && current_org_person.org_company_id == nil %>
	      <li class="sidebar_personal_purchases"><%= link_to "Personal Purchase History", trx_orders_list_personal_purchases_path %></li>
	    <% end %>
	    <!-- Only the COO, the operations chief, will be able to link his company to a bank account. -->
	    <% if current_org_person.typ_position_id == 1%>
	      <li class="sidebar_stripe_settings"><%= link_to "Payment Settings", org_people_stripe_settings_path %></li>
	    <% end %>  
  	</ul>

  	<ul class="nav nav-sidebar">
	    <!-- company_id is from the sessions_helper.id -->
	    <% if current_org_person != nil && current_org_person.org_company_id != nil %>
	      <li class="sidebar_company_info"><%= link_to "Company Information", org_company_path(current_org_person.org_company_id) %></li>
	      <li class="sidebar_company_people"><%= link_to "People", org_companies_people_path %></li>
	      <li class="sidebar_purchases"><%= link_to "Company Purchase History", trx_orders_list_purchases_path %></li>
	  
	      <% if company_typ.typ_company_id == 1 %>
	        
	      <% elsif company_typ.typ_company_id == 2 %>
	        
	      <% elsif company_typ.typ_company_id == 3 %>
	        <li class="sidebar_post_items_for_sale"><%= link_to "Post Items For Sale", new_org_product_path %></li>
	        <li class="sidebar_posted_items"><%= link_to "Posted Items", org_products_path %></li>
	        <li><%= link_to "Local Deliverers", org_companies_list_deliverers_path %></li>
	        <li class="sidebar_my_deliverers"><%= link_to "My Deliverers", org_companies_preferred_deliverers_path %></li> 
	        <li class="sidebar_orders"><%= link_to "Order Requests", org_products_orders_path %></li>
	        <li class="sidebar_completed_orders"><%= link_to "Completed Orders", org_products_completed_orders_path %></li>
	      <% end %>
	    <% else %>
	    <% end %>
	</ul>

</div>
<% end %>

app/views/layouts/_stripeConnect.html.erb
<% if Stripe::Account.retrieve('self').country.in? StripeManaged::ALLOWED %>
<div class="col-md-4 col-md-offset-4" id="stripe-managed">
	<center>
		<h3>Managed</h3>
		<p>Create a managed Stripe account in:</p>
	</center>
	<%= form_tag stripe_managed_path, method: :post do%>
		<%= select_tag 'country', options_for_select(StripeManaged::COUNTRIES.collect {|c| [ c[:name], c[:code] ] }), {:class => 'form-control'} %>
		<label class="tos">
			<%= check_box_tag 'tos'%> I accept the <a href='https://stripe.com/connect/account-terms', target="_blank">Stripe Connected Account Agreement</a>
		</label>
		<%= submit_tag "Create", :class => "btn btn-primary disabled" %>
	<% end %>
</div>
<% end %>

app/views/layouts/_stripeSettings.html.erb
<div class="col-md-11">
<% if current_org_person.managed?%>
	<center>
		<h2>Stripe Account Management</h2>
		<p>Account Type: <strong>Managed</strong></p>

		<!-- Current account status, whether the account can make charges or can receive transfers -->
		<div class="account-status">
			Status:
			<table>
				<% [@charges, @transfers].each do |text, yn| %>
					<tr>
						<td>
							<span class="label <%= yn ? 'label-primary' : 'label-danger'%>">
								<span class="fa <%= yn ? 'fa-check' : 'fa-times'%>"></span>
								<%= text %>
							</span>	
						</td>
					</tr>
				<% end %>
			</table>
		</div>
	</center>
	<!-- If we need more information from this user to keep their account in good standing -->
	<div class="col-md-7 col-md-offset-3">
		<% if current_org_person.stripe_account_status['fields_needed'].any? %>
			<hr>
			<div class="needed">
				<%= form_for :org_person, url: org_people_stripe_update_settings_url, html: {:class => 'form-horizontal'} do |f| %>
					<h3>Needed Information</h3>
					<% if current_org_person.stripe_account_status['due_by']%>
						<p>Due by: <strong><%= Time.at(current_org_person.stripe_account_status['due_by']).strfttime("%Y-%m-%d")%></strong></p>
					<% end %>
					<ul class="list-group">
						<% if @manager.needs?('bank_account')%>
							<li class="list-group-item" id="bank-account" data-publishable=<%= current_org_person.stripe_publishable_key%>>
								<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
								<h3>Bank Account</h3>
								<%= hidden_field_tag :bank_account_token %>
								<%= hidden_field_tag :currency, current_org_person.stripe_currency, :data => {:stripe => 'currency'} %>
								<div class="form-group">
									<label class="control-label col-xs-12 col-sm-3">Country: </label>
									<div class="col-xs-12 col-sm-9">
										<select class="form-control" data-stripe="country">
											<% @manager.supported_bank_account_countries.each do |country| %>
												<option value=<%= country[:code]%>><%= country[:name]%></option>
											<% end %>
										</select>
									</div>
								</div>
								<div class="form-group">
									<label class="control-label col-xs-12 col-sm-3">Account Number: </label>
									<div class="col-xs-12 col-sm-9">
										<%= text_field_tag nil, nil, {:class => "form-control", :data => {:stripe => 'account_number'}}%>
									</div>
								</div>
								<div class="form-group" id="bank-routing-container">
									<label class="control-label col-xs-12 col-sm-3">Routing Number: </label>
									<div class="col-xs-12 col-sm-9">
										<%= text_field_tag nil, nil, {:class => "form-control", :data => {:stripe => 'routing_number'}}%>
									</div>
								</div>
							</li>
						<% end %>
						<% if @manager.needs?('legal_entity.')%>
							<li class="list-group-item">
								<h3>Legal Entity</h3>
								<% if @manager.needs?('legal_entity.first_name')%>
									<div class="form-group">
										<label class="control-label col-xs-12 col-sm-3">First Name: </label>
										<div class="col-xs-12 col-sm-9">
											<%= text_field_tag 'legal_entity[first_name]', @manager.legal_entity.first_name, {:class => "form-control"}%>
										</div>
									</div>
								<% end %> 

								<% if @manager.needs?('legal_entity.last_name')%>
									<div class="form-group">
										<label class="control-label col-xs-12 col-sm-3">Last Name: </label>
										<div class="col-xs-12 col-sm-9">
											<%= text_field_tag 'legal_entity[last_name]', @manager.legal_entity.last_name, {:class => "form-control"}%>
										</div>
									</div>
								<% end %>

								<% if @manager.needs?('legal_entity.dob')%>
									<div class="form-group dob">
										<label class="control-label col-xs-12 col-sm-3">Date of Birth: </label>
										<div class="col-xs-12 col-sm-9">
											<%= date_select('legal_entity', 'dob',
											{
												selected: @date_selected,
												prompt: true,
												start_year: 90.years.ago.year,
												end_year: 13.years.ago.year
											}, {:class => 'form-control'}
											)%>
										</div>
									</div>
								<% end %>

								<% if @manager.needs?('legal_entity.personal_id_number')%>
									<div class="form-group">
										<label class="control-label col-xs-12 col-sm-3">Personal ID Number: </label>
										<div class="col-xs-12 col-sm-9">
											<%= text_field_tag 'legal_entity[personal_id_number]', nil, {:class => "form-control"}%>
										</div>
									</div>
								<% elsif @manager.needs?('legal_entity.ssn_last_4')%>
									<div class="form-group">
										<label class="control-label col-xs-12 col-sm-3">SSN Last 4: </label>
										<div class="col-xs-12 col-sm-9">
											<%= text_field_tag 'legal_entity[ssn_last_4]', nil, {:class => "form-control"}%>
										</div>
									</div>	
								<% end %>

								<% if @manager.needs?('legal_entity.address.line1')%>
									<div class="form-group">
										<label class="control-label col-xs-12 col-sm-3">Address Line 1: </label>
										<div class="col-xs-12 col-sm-9">
											<%= text_field_tag 'legal_entity[address][line1]', @manager.legal_entity.address.line1, {:class => "form-control"}%>
										</div>
									</div>	
								<% end %>

								<div class="form-group">
									<label class="control-label col-xs-12 col-sm-3">Address Line 2: </label>
									<div class="col-xs-12 col-sm-9">
										<%= text_field_tag 'legal_entity[address][line2]', @manager.legal_entity.address.line2, {:class => "form-control"}%>
									</div>
								</div>

								<% if @manager.needs?('legal_entity.address.city')%>
									<div class="form-group">
										<label class="control-label col-xs-12 col-sm-3">City: </label>
										<div class="col-xs-12 col-sm-9">
											<%= text_field_tag 'legal_entity[address][city]', @manager.legal_entity.address.city, {:class => "form-control"}%>
										</div>
									</div>
								<% end %>

								<% if @manager.needs?('legal_entity.address.address.state')%>
									<div class="form-group">
										<label class="control-label col-xs-12 col-sm-3">State/Province: </label>
										<div class="col-xs-12 col-sm-9">
											<%= text_field_tag 'legal_entity[address][state]', @manager.legal_entity.address.state, {:class => "form-control"}%>
										</div>
									</div>
								<% end %>

								<% if @manager.needs?('legal_entity.address.address.postal_code')%>
									<div class="form-group">
										<label class="control-label col-xs-12 col-sm-3">ZIP/Postal Code: </label>
										<div class="col-xs-12 col-sm-9">
											<%= text_field_tag 'legal_entity[address][postal_code]', @manager.legal_entity.address.postal_code, {:class => "form-control"}%>
										</div>
									</div>
								<% end %>
							</li>
							<center><%= f.submit 'Save Info', :class => 'btn btn-lg btn-primary stripe-save-info' %></center>
						<% end %>
					</ul>
				<% end %>
			</div>
		<% end %>
	</div>
<% end %>
</div>

app/views/layouts/_votebuttons.html.erb
   <% if current_org_person.voted_up_on? product%>
    <button type="button" class="btn btn-default thumbup voted" aria-label="Left Align">
      <span class="fa fa-thumbs-o-up" aria-hidden="true" vote="upvote" id="<%= product.id%>"></span>
  <% else %>
    <button type="button" class="btn btn-default thumbup" aria-label="Left Align">
      <span class="fa fa-thumbs-o-up" aria-hidden="true" vote="upvote" id="<%= product.id%>"></span>
  <% end %> 
</button>
  <% if current_org_person.voted_down_on? product%>
    <button type="button" class="btn btn-default thumbdown voted" aria-label="Left Align">
     <span class="fa fa-thumbs-o-down" aria-hidden="true" vote="downvote" id="<%= product.id%>"></span>
  <% else %>
    <button type="button" class="btn btn-default thumbdown" aria-label="Left Align">
      <span class="fa fa-thumbs-o-down" aria-hidden="true" vote="downvote" id="<%= product.id%>"></span>
  <% end %>
</button>